package cn.cm.union.dao;

import cn.cm.union.pojo.LoginInfo;
import cn.cm.union.pojo.LoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    long countByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int deleteByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int insert(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int insertSelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    List<LoginInfo> selectByExampleWithRowbounds(LoginInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    List<LoginInfo> selectByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    LoginInfo selectByPrimaryKey(Integer loginId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginInfo record);
}